services:
  - type: web
    name: nlw-22-computer-vision
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
    region: oregon
    plan: free
